=== materials-data-facility/data-schemas/schemas/record.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "MDF Record",
    "type": "object",
    "description": "Schema for record entry in MDF.",
    "properties": {
        "mdf": {
            "$ref": "mdf.json#/properties/mdf"
        },
        "files": {
            "$ref": "files.json#/properties/files"
        },
        "material": {
            "$ref": "material.json#/properties/material"
        },
        "molecule": {
            "$ref": "molecule.json#/properties/molecule"
        },
        "origin": {
            "$ref": "origin.json#/properties/origin"
        },
        "calphad": {
            "$ref": "calphad.json#/properties/calphad"
        },
        "crystal_structure": {
            "$ref": "crystal_structure.json#/properties/crystal_structure"
        },
        "dft": {
            "$ref": "dft.json#/properties/dft"
        },
        "electron_microscopy": {
            "$ref": "electron_microscopy.json#/properties/electron_microscopy"
        },
        "image": {
            "$ref": "image.json#/properties/image"
        },
        "raman": {
            "$ref": "raman.json#/properties/raman"
        },
        "md": {
            "$ref": "md.json#/properties/md"
        },
        "xrd": {
            "$ref": "xrd.json#/properties/xrd"
        },
        "cross_reference": {
            "$ref": "cross_reference.json#/properties/cross_reference"
        },
        "custom": {
            "$ref": "custom.json#/properties/custom"
        },
        "projects": {
            "$ref": "projects.json#/properties/projects"
        }
    },
    "additionalProperties": false,
    "required": [
        "mdf",
        "files"
    ]
}

=== materials-data-facility/data-schemas/tests/test_files/record/success_min_alt.json
{
    "mdf": {
        "source_name": "foobar",
        "source_id": "foobar_v1-2",
        "mdf_id": "abcd123",
        "scroll_id": 0,
        "parent_id": "abcd123",
        "acl": ["public"],
        "ingest_date": "2018-11-15T17:04:10.315060Z",
        "resource_type": "dataset",
        "version": 1,
        "organizations": ["Repo1", "Repo2"]
    },
    "files": [{
        "data_type": "type",
        "filename": "data.txt"
    }],
    "material": {},
    "origin": {},
    "calphad": {},
    "crystal_structure": {
        "space_group_number": 5
    },
    "dft": {},
    "electron_microscopy": {},
    "image": {},
    "md": {},
    "xrd": {}
}

=== materials-data-facility/data-schemas/tests/test_files/record/success_maximal.json
{
    "mdf": {
        "source_name": "foobar",
        "source_id": "foobar_v1-2",
        "scroll_id": 0,
        "acl": ["public"],
        "ingest_date": "2018-11-15T17:04:10.315060Z",
        "resource_type": "dataset",
        "version": 1,
        "organizations": ["Repo1", "Repo2"]
    },
    "files": [{
        "globus": "globus://abcdef123/path/data.txt",
        "url": "https://example.com/data.txt",
        "data_type": "type",
        "mime_type": "text",
        "length": 5000,
        "filename": "data.txt",
        "md5": "abcdef123",
        "sha1": "abcdef123",
        "sha256": "abcdef123",
        "sha512": "abcdef123"
    }, {
        "data_type": "type",
        "filename": "data.txt"
    }],
    "material": {
        "composition": "N12O",
        "elements": ["N", "O"]
    },
    "origin": {
        "name": "Software.exe",
        "version": "1.1.1.2",
        "creator": "DevCorp",
        "type": "other"
    },
    "calphad": {
        "phases": [
            "Assembly",
            "denial",
            "acceptance"
        ]
    },
    "crystal_structure": {
        "space_group_number": 5,
        "number_of_atoms": 1.5,
        "volume": 5.5,
        "stoichiometry": "A2B"
    },
    "cross_reference": {
        "icsd": 555,
        "cod": 5555,
        "amcsd": 55555
    },
    "dft": {
        "converged": true,
        "exchange_correlation_functional": "Yes",
        "cutoff_energy": 42.123
    },
    "electron_microscopy": {
        "acquisition_mode": "Secondary electron",
        "beam_energy": 5,
        "detector": "On",
        "magnification": 5,
        "collection_angle": 360,
        "emission_current": 1
    },
    "image": {
        "shape": [
            1, 2, 3, 999
        ]
    },
    "raman": {
        "peaks": [{
            "label": "g",
            "width": 5,
            "center": 1
        }]
    },
    "md": {
        "ensemble": "Something",
        "particle_count": 5,
        "timesteps": 500,
        "simulation_time": {
            "value": 159,
            "units": "spherical cows"
        },
        "potential": "Untapped"
    },
    "xrd": {
        "wavelength": 5,
        "xray_source": "Microwave",
        "sample_condition": "Good for what it is",
        "detector_dimensionality": 18
    },
    "custom": {
        "foo": "bar",
        "baz": "123"
    },
    "projects": {
        "nanomfg": {
            "base_pressure": 19.1,
            "carbon_source": "CH4"
        }
    }
}
